<x-app-layout>
    <x-slot name="header"><h2 class="text-xl font-semibold text-slate-900">Import Preview</h2></x-slot>
    <div class="mx-auto max-w-[1500px] space-y-6 px-4 py-8 sm:px-6 lg:px-8">
        @if(session('success'))<div class="rounded-xl border border-emerald-200 bg-emerald-50 p-4 text-emerald-800">{{ session('success') }}</div>@endif
        @if($errors->any())<div class="rounded-xl border border-red-200 bg-red-50 p-4 text-red-800">{{ $errors->first() }}</div>@endif
        <section class="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm">
            <div class="flex flex-wrap items-start justify-between gap-4"><div><h3 class="text-lg font-semibold">{{ $batch->original_filename }}</h3><p class="text-sm text-slate-500">Batch {{ $batch->batch_number }}</p></div><div class="flex gap-2"><a href="{{ route('admin.child-labor-imports.errors',$batch) }}" class="rounded-xl border border-slate-300 px-4 py-2 text-sm font-semibold">Download issues</a>@if($batch->status==='preview')<form method="POST" action="{{ route('admin.child-labor-imports.commit',$batch) }}" onsubmit="return confirm('Import all valid and warning rows?');">@csrf<button class="rounded-xl bg-emerald-600 px-4 py-2 text-sm font-semibold text-white">Commit import</button></form>@endif</div></div>
            <div class="mt-6 grid gap-4 sm:grid-cols-2 lg:grid-cols-4"><div class="rounded-xl bg-slate-50 p-4"><p class="text-xs uppercase text-slate-500">Total</p><p class="text-2xl font-bold">{{ $batch->total_rows }}</p></div><div class="rounded-xl bg-emerald-50 p-4"><p class="text-xs uppercase text-emerald-700">Valid</p><p class="text-2xl font-bold text-emerald-800">{{ $batch->valid_rows }}</p></div><div class="rounded-xl bg-amber-50 p-4"><p class="text-xs uppercase text-amber-700">Warnings</p><p class="text-2xl font-bold text-amber-800">{{ $batch->warning_rows }}</p></div><div class="rounded-xl bg-red-50 p-4"><p class="text-xs uppercase text-red-700">Errors</p><p class="text-2xl font-bold text-red-800">{{ $batch->error_rows }}</p></div></div>
        </section>
        <form method="GET" class="flex gap-3"><select name="status" class="rounded-xl border-slate-300"><option value="">All rows</option>@foreach(['valid','warning','error'] as $status)<option value="{{ $status }}" @selected(request('status')===$status)>{{ ucfirst($status) }}</option>@endforeach</select><button class="rounded-xl bg-slate-800 px-4 py-2 text-white">Filter</button></form>
        <section class="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm"><div class="overflow-x-auto"><table class="min-w-full divide-y divide-slate-200 text-sm"><thead class="bg-slate-50 text-left text-xs uppercase text-slate-500"><tr><th class="px-4 py-3">Row</th><th class="px-4 py-3">Child ID</th><th class="px-4 py-3">Name</th><th class="px-4 py-3">Status</th><th class="px-4 py-3">Warnings / Errors</th><th class="px-4 py-3">Result</th></tr></thead><tbody class="divide-y divide-slate-100">@foreach($rows as $row)<tr class="align-top"><td class="px-4 py-4">{{ $row->sheet_row }}</td><td class="px-4 py-4">{{ $row->child_id_number ?: '—' }}</td><td class="px-4 py-4 font-medium">{{ $row->child_name ?: '—' }}</td><td class="px-4 py-4"><span class="rounded-full px-2.5 py-1 text-xs font-semibold {{ $row->status==='valid'?'bg-emerald-100 text-emerald-700':($row->status==='warning'?'bg-amber-100 text-amber-700':'bg-red-100 text-red-700') }}">{{ ucfirst($row->status) }}</span></td><td class="max-w-xl px-4 py-4 text-xs text-slate-600">@foreach($row->warnings??[] as $message)<div>⚠ {{ $message }}</div>@endforeach @foreach($row->errors??[] as $message)<div class="text-red-700">✕ {{ $message }}</div>@endforeach</td><td class="px-4 py-4">{{ $row->resolution ?: 'Pending' }}</td></tr>@endforeach</tbody></table></div><div class="p-4">{{ $rows->links() }}</div></section>
    </div>
</x-app-layout>
