<?php

return [
    'accepted_extensions' => ['xlsx', 'xls'],
    'max_file_kb' => 20480,
    'header_row' => 1,
    'first_data_row' => 2,
    'expected_column_count' => 129,

    /*
    | The source workbook contains one intentionally blank heading at column 13.
    | Mapping by fixed column number prevents later values from shifting.
    */
    'columns' => [
        1 => 'child_id_number',
        2 => 'full_name',
        3 => 'present_region',
        4 => 'present_province',
        5 => 'present_district',
        6 => 'present_city',
        7 => 'present_barangay',
        8 => 'present_purok',
        9 => 'contact_number',
        10 => 'sex',
        11 => 'birth_date',
        12 => 'birth_date_basis',
        13 => 'source_reference_date',
        14 => 'age_2024',
        15 => 'recorded_age',
        16 => 'birth_certificate',
        17 => 'place_of_birth_text',
        18 => 'birth_region',
        19 => 'birth_province',
        20 => 'birth_district',
        21 => 'birth_city',
        22 => 'birth_barangay',
        23 => 'birth_purok',
        24 => 'religion',
        25 => 'is_indigenous_person',
        26 => 'living_with',
        27 => 'living_with_person',
        28 => 'living_with_reason',
        29 => 'dwelling_unit',
        30 => 'ever_attended_school',
        31 => 'currently_attending_school',
        32 => 'learning_reference_number',
        33 => 'highest_grade_completed',
        34 => 'form_of_education',
        35 => 'age_stopped_schooling',
        36 => 'school_nonattendance_reason',
        37 => 'has_disability',
        38 => 'disability_description',
        39 => 'needs_disability_assessment',
        40 => 'height_cm',
        41 => 'weight_kg',
        42 => 'medical_conditions',
        43 => 'needs_medical_assessment',
        44 => 'family_ailment_history',
        45 => 'child_tasks',
        46 => 'employer_name',
        47 => 'employer_contact',
        48 => 'employer_region',
        49 => 'employer_province',
        50 => 'employer_city',
        51 => 'employer_barangay',
        52 => 'employer_purok',
        53 => 'work_arrangement',
        54 => 'working_hours_per_day',
        55 => 'working_days_per_week',
        56 => 'work_time',
        57 => 'age_started_working',
        58 => 'work_hazards',
        59 => 'payment_basis',
        60 => 'average_monthly_income',
        61 => 'earnings_usage',
        62 => 'adult_supervision',
        63 => 'work_supervisor',
        64 => 'family_1', 65 => 'family_2', 66 => 'family_3', 67 => 'family_4',
        68 => 'family_5', 69 => 'family_6', 70 => 'family_7', 71 => 'family_8',
        72 => 'family_9', 73 => 'family_10', 74 => 'family_11', 75 => 'family_12',
        76 => 'is_4ps_household',
        77 => 'household_id_number',
        78 => 'availed_service_1', 79 => 'availed_service_2', 80 => 'availed_service_3',
        81 => 'availed_service_4', 82 => 'availed_service_5', 83 => 'availed_service_6',
        84 => 'availed_service_7', 85 => 'availed_service_8', 86 => 'availed_service_9',
        87 => 'availed_service_10', 88 => 'availed_service_11', 89 => 'availed_service_12',
        90 => 'requested_service_1', 91 => 'requested_service_2', 92 => 'requested_service_3',
        93 => 'requested_service_4', 94 => 'requested_service_5', 95 => 'requested_service_6',
        96 => 'requested_service_7', 97 => 'requested_service_8', 98 => 'requested_service_9',
        99 => 'requested_service_10', 100 => 'requested_service_11', 101 => 'requested_service_12',
        102 => 'enumerator_name',
        103 => 'interview_date',
        104 => 'needs_assessed',
        105 => 'already_referred',
        106 => 'referral_agencies',
        107 => 'referral_date',
        108 => 'already_provided_services',
        109 => 'services_provided_initial',
        110 => 'service_agency_initial',
        111 => 'service_date_initial',
        112 => 'services_provided_2022',
        113 => 'service_agency_2022',
        114 => 'service_date_2022',
        115 => 'services_provided_2023',
        116 => 'service_agency_2023',
        117 => 'service_date_2023',
        118 => 'services_provided_2024',
        119 => 'service_agency_2024',
        120 => 'service_date_2024',
        121 => 'monitored_by',
        122 => 'monitor_position',
        123 => 'monitoring_date',
        124 => 'withdrawn_from_child_labor',
        125 => 'withdrawal_indicator',
        126 => 'not_yet_withdrawn',
        127 => 'removed',
        128 => 'remarks',
        129 => 'additional_remarks',
    ],

    'required_fields' => [
        'child_id_number', 'full_name', 'present_region', 'present_province',
        'present_city', 'present_barangay', 'sex', 'birth_date',
    ],

    'placeholder_values' => ['', '-', '--', 'n/a', 'na', 'none', 'not available', 'unknown'],
];
