@php
    $value = function (
        mixed $model,
        array $keys,
        mixed $default = 'Not recorded'
    ): mixed {
        if (! $model) {
            return $default;
        }

        foreach ($keys as $key) {
            $result = data_get(
                $model,
                $key
            );

            if (filled($result)) {
                return $result;
            }
        }

        return $default;
    };

    $money = function (
        mixed $amount
    ): string {
        if (
            $amount === null
            || $amount === ''
        ) {
            return 'Not recorded';
        }

        return '₱'.number_format(
            (float) $amount,
            2
        );
    };

    $birth = $childLaborer
        ->birthInformation;

    $address = $childLaborer
        ->residentialAddress;
@endphp

<section class="report-header">
    <div>
        <p class="report-kicker">
            Child Labor Prevention and Monitoring Information System
        </p>

        <h1>
            Comprehensive Child Laborer Profile
        </h1>

        <p class="report-subtitle">
            {{ $childLaborer->profile_number }}
            ·
            {{ $childLaborer->status }}
        </p>
    </div>

    @if ($photoDataUri)
        <img
            src="{{ $photoDataUri }}"
            alt="Child laborer profile photograph"
            class="profile-photo"
        >
    @endif
</section>

<section class="report-meta">
    <div>
        <strong>Generated by:</strong>
        {{ $generatedBy }}
    </div>

    <div>
        <strong>Generated:</strong>
        {{ $generatedAt->format(
            'F d, Y h:i A'
        ) }}
    </div>

    <div>
        <strong>Assigned officer:</strong>
        {{ $childLaborer
            ->assignedOfficer?->name
            ?? 'Not assigned' }}
    </div>
</section>

<section class="report-section">
    <h2>Personal Information</h2>

    <div class="detail-grid">
        <div>
            <span>Full Name</span>
            <strong>
                {{ $childLaborer->full_name }}
            </strong>
        </div>

        <div>
            <span>Sex</span>
            <strong>
                {{ $childLaborer->sex }}
            </strong>
        </div>

        <div>
            <span>Birth Date</span>
            <strong>
                {{ $childLaborer
                    ->birth_date
                    ?->format('F d, Y')
                    ?? 'Not recorded' }}
            </strong>
        </div>

        <div>
            <span>Age</span>
            <strong>
                {{ $childLaborer->birth_date
                    ? $childLaborer
                        ->birth_date
                        ->age.' years'
                    : 'Not recorded' }}
            </strong>
        </div>

        <div>
            <span>Civil Status</span>
            <strong>
                {{ $childLaborer
                    ->civil_status
                    ?: 'Not recorded' }}
            </strong>
        </div>

        <div>
            <span>Nationality</span>
            <strong>
                {{ $childLaborer
                    ->nationality
                    ?: 'Not recorded' }}
            </strong>
        </div>

        <div>
            <span>Religion</span>
            <strong>
                {{ $childLaborer
                    ->religion
                    ?: 'Not recorded' }}
            </strong>
        </div>

        <div>
            <span>Contact Number</span>
            <strong>
                {{ $childLaborer
                    ->contact_number
                    ?: 'Not recorded' }}
            </strong>
        </div>
    </div>
</section>

<section class="report-section">
    <h2>Birth and Residential Information</h2>

    <div class="detail-grid">
        <div>
            <span>Place of Birth</span>
            <strong>
                {{ $birth?->place_of_birth
                    ?: 'Not recorded' }}
            </strong>
        </div>

        <div>
            <span>Birth Barangay</span>
            <strong>
                {{ $birth?->barangay?->name
                    ?? 'Not recorded' }}
            </strong>
        </div>

        <div>
            <span>Birth City / Municipality</span>
            <strong>
                {{ $birth?->locality?->name
                    ?? 'Not recorded' }}
            </strong>
        </div>

        <div>
            <span>Birth Province</span>
            <strong>
                {{ $birth?->province?->name
                    ?? 'Not recorded' }}
            </strong>
        </div>

        <div class="wide">
            <span>Current Residential Address</span>
            <strong>
                {{ $addressText }}
            </strong>
        </div>
    </div>
</section>

<section class="report-section">
    <h2>Parent and Guardian Information</h2>

    <table>
        <thead>
            <tr>
                <th>Name</th>
                <th>Relationship</th>
                <th>Contact</th>
                <th>Occupation</th>
                <th>Education</th>
                <th>Income</th>
                <th>Primary</th>
            </tr>
        </thead>

        <tbody>
            @forelse (
                $childLaborer
                    ->parentGuardians
                as $guardian
            )
                <tr>
                    <td>
                        {{ $guardian->full_name }}
                    </td>

                    <td>
                        {{ $value(
                            $guardian,
                            [
                                'relationship',
                                'relationship_to_child',
                            ]
                        ) }}
                    </td>

                    <td>
                        {{ $value(
                            $guardian,
                            [
                                'contact_number',
                                'contact_no',
                            ]
                        ) }}
                    </td>

                    <td>
                        {{ $value(
                            $guardian,
                            ['occupation']
                        ) }}
                    </td>

                    <td>
                        {{ $value(
                            $guardian,
                            [
                                'educational_attainment',
                                'education',
                            ]
                        ) }}
                    </td>

                    <td>
                        {{ $money(
                            $value(
                                $guardian,
                                [
                                    'monthly_income',
                                    'income',
                                ],
                                null
                            )
                        ) }}
                    </td>

                    <td>
                        {{ $guardian->is_primary
                            ? 'Yes'
                            : 'No' }}
                    </td>
                </tr>
            @empty
                <tr>
                    <td colspan="7">
                        No parent or guardian information recorded.
                    </td>
                </tr>
            @endforelse
        </tbody>
    </table>
</section>

<section class="report-section">
    <h2>Household Members</h2>

    <table>
        <thead>
            <tr>
                <th>Name</th>
                <th>Relationship</th>
                <th>Sex</th>
                <th>Birth Date</th>
                <th>Education</th>
                <th>Occupation</th>
                <th>Income</th>
            </tr>
        </thead>

        <tbody>
            @forelse (
                $childLaborer
                    ->householdMembers
                as $member
            )
                <tr>
                    <td>
                        {{ $member->full_name }}
                    </td>

                    <td>
                        {{ $value(
                            $member,
                            [
                                'relationship',
                                'relationship_to_child',
                            ]
                        ) }}
                    </td>

                    <td>
                        {{ $value(
                            $member,
                            ['sex']
                        ) }}
                    </td>

                    <td>
                        {{ $member->birth_date
                            ?->format('F d, Y')
                            ?? 'Not recorded' }}
                    </td>

                    <td>
                        {{ $value(
                            $member,
                            [
                                'educational_attainment',
                                'education',
                            ]
                        ) }}
                    </td>

                    <td>
                        {{ $value(
                            $member,
                            ['occupation']
                        ) }}
                    </td>

                    <td>
                        {{ $money(
                            $value(
                                $member,
                                [
                                    'monthly_income',
                                    'income',
                                ],
                                null
                            )
                        ) }}
                    </td>
                </tr>
            @empty
                <tr>
                    <td colspan="7">
                        No household member information recorded.
                    </td>
                </tr>
            @endforelse
        </tbody>
    </table>
</section>

<section class="report-section">
    <h2>Education Records</h2>

    <table>
        <thead>
            <tr>
                <th>School</th>
                <th>Grade / Year</th>
                <th>School Year</th>
                <th>Status</th>
                <th>Dates</th>
                <th>Current</th>
            </tr>
        </thead>

        <tbody>
            @forelse (
                $childLaborer
                    ->educationRecords
                as $education
            )
                <tr>
                    <td>
                        <strong>
                            {{ $education
                                ->school_name
                                ?: 'Not recorded' }}
                        </strong>

                        @if (
                            $education
                                ->school_address
                        )
                            <br>

                            {{ $education
                                ->school_address }}
                        @endif
                    </td>

                    <td>
                        {{ $education
                            ->grade_year_level
                            ?: 'Not recorded' }}
                    </td>

                    <td>
                        {{ $education
                            ->school_year
                            ?: 'Not recorded' }}
                    </td>

                    <td>
                        {{ $education
                            ->enrollment_status
                            ?: 'Not recorded' }}

                        @if (
                            $education
                                ->reason_not_attending
                        )
                            <br>

                            Reason:
                            {{ $education
                                ->reason_not_attending }}
                        @endif
                    </td>

                    <td>
                        {{ $education
                            ->date_enrolled
                            ?->format('M d, Y')
                            ?? '—' }}

                        to

                        {{ $education
                            ->date_ended
                            ?->format('M d, Y')
                            ?? 'Present / unknown' }}
                    </td>

                    <td>
                        {{ $education->is_current
                            ? 'Yes'
                            : 'No' }}
                    </td>
                </tr>
            @empty
                <tr>
                    <td colspan="6">
                        No education record available.
                    </td>
                </tr>
            @endforelse
        </tbody>
    </table>
</section>

<section class="report-section">
    <h2>Employment and Working Conditions</h2>

    @forelse (
        $childLaborer
            ->employmentRecords
        as $employment
    )
        <article class="record-card">
            <div class="detail-grid">
                <div>
                    <span>Employer</span>
                    <strong>
                        {{ $employment
                            ->employer_name
                            ?: 'Not recorded' }}
                    </strong>
                </div>

                <div>
                    <span>Occupation</span>
                    <strong>
                        {{ $employment
                            ->occupation }}
                    </strong>
                </div>

                <div>
                    <span>Work Type</span>
                    <strong>
                        {{ $employment
                            ->work_type }}
                    </strong>
                </div>

                <div>
                    <span>Arrangement</span>
                    <strong>
                        {{ $employment
                            ->employment_arrangement }}
                    </strong>
                </div>

                <div>
                    <span>Schedule</span>
                    <strong>
                        {{ $employment
                            ->days_per_week }}
                        day(s) per week,
                        {{ $employment
                            ->hours_per_day }}
                        hour(s) per day
                    </strong>
                </div>

                <div>
                    <span>Income</span>
                    <strong>
                        {{ $money(
                            $employment
                                ->income_amount
                        ) }}
                        /
                        {{ $employment
                            ->income_frequency }}
                    </strong>
                </div>

                <div>
                    <span>Period</span>
                    <strong>
                        {{ $employment
                            ->start_date
                            ?->format('M d, Y') }}

                        to

                        {{ $employment
                            ->end_date
                            ?->format('M d, Y')
                            ?? 'Present' }}
                    </strong>
                </div>

                <div>
                    <span>Current Employment</span>
                    <strong>
                        {{ $employment->is_current
                            ? 'Yes'
                            : 'No' }}
                    </strong>
                </div>
            </div>

            <h3>Recorded Work Hazards</h3>

            <table>
                <thead>
                    <tr>
                        <th>Hazard</th>
                        <th>Frequency</th>
                        <th>Description</th>
                        <th>Unsafe Conditions</th>
                        <th>PPE</th>
                    </tr>
                </thead>

                <tbody>
                    @forelse (
                        $employment
                            ->workHazards
                        as $hazard
                    )
                        <tr>
                            <td>
                                {{ $hazard
                                    ->hazard_type }}
                            </td>

                            <td>
                                {{ $hazard
                                    ->exposure_frequency }}
                            </td>

                            <td>
                                {{ $hazard
                                    ->hazard_description }}
                            </td>

                            <td>
                                @php
                                    $flags = collect([
                                        $hazard->heavy_work
                                            ? 'Heavy work'
                                            : null,

                                        $hazard->long_hours
                                            ? 'Long hours'
                                            : null,

                                        $hazard->night_work
                                            ? 'Night work'
                                            : null,

                                        $hazard->unsafe_conditions
                                            ? 'Unsafe conditions'
                                            : null,
                                    ])->filter();
                                @endphp

                                {{ $flags->isNotEmpty()
                                    ? $flags->implode(', ')
                                    : 'None recorded' }}
                            </td>

                            <td>
                                {{ $hazard->ppe_provided
                                    ? 'Provided'
                                    : 'Not provided' }}

                                @if (
                                    $hazard
                                        ->ppe_description
                                )
                                    <br>

                                    {{ $hazard
                                        ->ppe_description }}
                                @endif
                            </td>
                        </tr>
                    @empty
                        <tr>
                            <td colspan="5">
                                No work hazard recorded for this employment.
                            </td>
                        </tr>
                    @endforelse
                </tbody>
            </table>
        </article>
    @empty
        <p class="empty">
            No employment information recorded.
        </p>
    @endforelse
</section>

@if ($includeSensitive)
    <section class="report-section sensitive">
        <h2>Health Information — Restricted</h2>

        <table>
            <thead>
                <tr>
                    <th>Assessment</th>
                    <th>Condition / Disability</th>
                    <th>Injury / Treatment</th>
                    <th>Complaints</th>
                    <th>Mental Health</th>
                    <th>Current</th>
                </tr>
            </thead>

            <tbody>
                @forelse (
                    $childLaborer
                        ->healthInformationRecords
                    as $health
                )
                    <tr>
                        <td>
                            {{ $health
                                ->assessment_date
                                ->format('F d, Y') }}
                        </td>

                        <td>
                            {{ $health
                                ->health_condition
                                ?: 'No condition recorded' }}

                            <br>

                            Disability:
                            {{ $health
                                ->has_disability
                                ? (
                                    $health
                                        ->disability_details
                                    ?: 'Reported'
                                )
                                : 'Not reported' }}
                        </td>

                        <td>
                            Injury:
                            {{ $health
                                ->injury_history
                                ?: 'None recorded' }}

                            <br>

                            Treatment:
                            {{ $health
                                ->treatment_received
                                ?: 'None recorded' }}
                        </td>

                        <td>
                            {{ $health
                                ->current_complaints
                                ?: 'None recorded' }}
                        </td>

                        <td>
                            {{ $health
                                ->mental_health_concerns
                                ?: 'None recorded' }}
                        </td>

                        <td>
                            {{ $health->is_current
                                ? 'Yes'
                                : 'No' }}
                        </td>
                    </tr>
                @empty
                    <tr>
                        <td colspan="6">
                            No health information recorded.
                        </td>
                    </tr>
                @endforelse
            </tbody>
        </table>
    </section>
@endif

<section class="report-section">
    <h2>Interventions and Assistance</h2>

    <table>
        <thead>
            <tr>
                <th>Type</th>
                <th>Provider</th>
                <th>Description</th>
                <th>Dates</th>
                <th>Value</th>
                <th>Status</th>
            </tr>
        </thead>

        <tbody>
            @forelse (
                $childLaborer
                    ->interventions
                as $intervention
            )
                <tr>
                    <td>
                        {{ $intervention
                            ->intervention_type }}
                    </td>

                    <td>
                        {{ $intervention
                            ->provider }}
                    </td>

                    <td>
                        {{ $intervention
                            ->description }}

                        @if (
                            $intervention->remarks
                        )
                            <br>

                            Remarks:
                            {{ $intervention
                                ->remarks }}
                        @endif
                    </td>

                    <td>
                        {{ $intervention
                            ->date_provided
                            ?->format('M d, Y')
                            ?? 'Not provided' }}

                        to

                        {{ $intervention
                            ->date_completed
                            ?->format('M d, Y')
                            ?? 'Not completed' }}
                    </td>

                    <td>
                        {{ $money(
                            $intervention->amount
                        ) }}
                    </td>

                    <td>
                        {{ $intervention->status }}
                    </td>
                </tr>
            @empty
                <tr>
                    <td colspan="6">
                        No intervention has been recorded.
                    </td>
                </tr>
            @endforelse
        </tbody>
    </table>
</section>

@if ($includeSensitive)
    <section class="report-section sensitive">
        <h2>Audit Schedules and Evaluations — Restricted</h2>

        @forelse (
            $childLaborer
                ->auditSchedules
            as $auditSchedule
        )
            <article class="record-card">
                <div class="detail-grid">
                    <div>
                        <span>Scheduled</span>
                        <strong>
                            {{ $auditSchedule
                                ->scheduled_at
                                ->format(
                                    'F d, Y h:i A'
                                ) }}
                        </strong>
                    </div>

                    <div>
                        <span>Status</span>
                        <strong>
                            {{ $auditSchedule->status }}
                        </strong>
                    </div>

                    <div>
                        <span>Assigned Admin</span>
                        <strong>
                            {{ $auditSchedule
                                ->assignedAdministrator
                                ->name }}
                        </strong>
                    </div>

                    <div>
                        <span>Location</span>
                        <strong>
                            {{ $auditSchedule->location
                                ?: 'Not recorded' }}
                        </strong>
                    </div>
                </div>

                <table>
                    <thead>
                        <tr>
                            <th>Date</th>
                            <th>Evaluator</th>
                            <th>Findings</th>
                            <th>Recommendations</th>
                            <th>Status</th>
                        </tr>
                    </thead>

                    <tbody>
                        @forelse (
                            $auditSchedule
                                ->evaluations
                            as $evaluation
                        )
                            <tr>
                                <td>
                                    {{ $evaluation
                                        ->evaluation_date
                                        ->format(
                                            'F d, Y'
                                        ) }}
                                </td>

                                <td>
                                    {{ $evaluation
                                        ->evaluator
                                        ->name }}
                                </td>

                                <td>
                                    {{ $evaluation
                                        ->findings
                                        ?: 'Not recorded' }}
                                </td>

                                <td>
                                    {{ $evaluation
                                        ->recommendations
                                        ?: 'Not recorded' }}
                                </td>

                                <td>
                                    {{ $evaluation->status }}
                                </td>
                            </tr>
                        @empty
                            <tr>
                                <td colspan="5">
                                    No evaluation recorded.
                                </td>
                            </tr>
                        @endforelse
                    </tbody>
                </table>
            </article>
        @empty
            <p class="empty">
                No audit schedule recorded.
            </p>
        @endforelse
    </section>
@endif

<section class="report-section">
    <h2>Available Profile Documents</h2>

    <table>
        <thead>
            <tr>
                <th>Document</th>
                <th>Type</th>
                <th>File Size</th>
                <th>Uploaded</th>
                <th>Uploader</th>
                <th>Confidential</th>
            </tr>
        </thead>

        <tbody>
            @forelse (
                $childLaborer->documents
                as $document
            )
                <tr>
                    <td>
                        {{ $document
                            ->original_name }}
                    </td>

                    <td>
                        {{ $document
                            ->document_type }}
                    </td>

                    <td>
                        {{ $document
                            ->formatted_file_size }}
                    </td>

                    <td>
                        {{ $document
                            ->uploaded_at
                            ->format(
                                'F d, Y h:i A'
                            ) }}
                    </td>

                    <td>
                        {{ $document
                            ->uploader?->name
                            ?? 'Unknown user' }}
                    </td>

                    <td>
                        {{ $document
                            ->is_confidential
                            ? 'Yes'
                            : 'No' }}
                    </td>
                </tr>
            @empty
                <tr>
                    <td colspan="6">
                        No available document.
                    </td>
                </tr>
            @endforelse
        </tbody>
    </table>
</section>